---
title: intro material
author: Ben Bolker
bibliography: ../vis.bib
csl: reflist2.csl
output:
  ioslides_presentation
---
<!-- 
apa.csl is a slightly hacked version of APA 
  (modified for "et al" after 2 authors in text)
-->
<!-- .refs is style for reference page (small text) -->
<style>
.refs {
   font-size: 16px;
}
h2 { 
 color: #3399ff;		
}
h3 { 
 color: #3399ff;		
}
.title-slide {
   background-color: #55bbff;
}
</style>
<!--    content: url(https://i.creativecommons.org/l/by-sa/4.0/88x31.png)
>
<!-- Limit image width and height -->
<style type="text/css">
img {     
  max-height: 560px;     
  max-width: 800px; 
}
</style>

```{r setup,echo=FALSE,message=FALSE}
library("ggplot2"); theme_set(theme_classic())
library("reshape2")
library("ggExtra")
library("MASS")
library("knitr")
opts_chunk$set(echo=FALSE,fig.width=4,fig.height=4,out.width=400)
```

# Course structure

## Course goals

General introduction to data viz principles and tools

## Course structures

- lectures from professors on basic ideas (first half)
- in-class work
- homework
- lectures from students on topics/advanced ideas (second half)

# Tools

## Version control

- Git: distributed version control system
- GitHub: centralized version control server
    - alternatives: BitBucket, GitLab, ...
- Git *clients*: software for working with Git on your computer
    - command-line (e.g. `git add foo.rmd`)
	- RStudio
	- others (GitHub desktop etc.)

## Basic Git workflow with RStudio

- create **repository** on Github
- copy repository to local machine
     - `git clone`
	 - RStudio: `File` > `New Project` > `Version Control` > `Git` > fill in name from "Clone" button on GH
	 
- - -

- repeat:
	 - **pull** (fetch and integrate changes from GH) [`git pull`]
		  - RStudio: Git panel > click blue down-arrow
     - do stuff (create, edit files, etc.)
	 - **stage**  [`git add`]
		  - RStudio: Git panel > click "Staged" button
     - **commit** [`git commit`]
		  - RStudio: Git panel > click "Commit" icon >  
enter commit message > click "Commit" button (*ignore "amend previous commit" button!*)
	 - **push** [`git push`]
		  - RStudio: Git panel > click green up-arrow

## tidyverse 

- set of R packages: https://www.tidyverse.org/
- advantages
    - expressiveness
    - speed
	- new hotness
- disadvantages
    - minor incompatibilities with base R
	- rapid evolution
	- non-standard evaluation

## tidyverse: big ideas

- piping
- new verbs
- tibbles

# types of data visualization

## exploratory

- find patterns in data, explore hypotheses
- emphasize **robust** approaches
- minimize (parametric) assumptions

## diagnostic

- evaluate assumptions of a model
    - normality
	- homoscedasticity
	- lack of bias/goodness of fit
- easily spot deviations
- identify outliers and influential points

## inferential

- coefficient plots
- replacement for tables
- also: tests of inference @wickham_graphical_2010

## expository: data-viz

- tell an accurate story
- high information density

## presentation: info-viz

- grab attention/engage/sell/entertain
- "puzzle" graphics

## dashboards

- present a quick overview of a data set
- user control

## dynamic

- engage
- allow reader to drill down

## questions

- should 
<!-- http://stackoverflow.com/questions/30990262/applying-css-to-make-code-smaller-in-ioslides-style -->

## References {.refs}


