

---
title: "Introduction"
author: "Ben Bolker"
date:  "`r format(Sys.time(), '%H:%M %d %B %Y')`"
output: tufte_handout
bibliography: ../nonlin.bib
header-includes:
   - usepackage[utf8]{inputenc}
---

# Overview/logistics

* applied focus
* all class materials at https://github.com/bbolker/stat744
* class-led, in pairs
    * Monday: lecture
	* Thursday: practical exercise
* [topics](../topics.md)

# Big picture

* dynamical models
   * involve both *process* and *observation* error/noise
   
-----------------------------------------------------------------------------
time          process         state          space           model     
------------  -------------   -----------    ----------      -----------------
continuous    deterministic   continuous                     ODE 

continuous    stochastic      continuous                     stochastic ODE 

continuous    deterministic,  continuous                     difference equation
              stochastic
			   
discrete	  stochastic      discrete                       Markov process
			   
continuous    stochastic      discrete                       continuous-time MP
 
----------------------------------------------------------------------

* nonlinearity
   * variance changes unpredictably
* non-Gaussian 
   * constrained bounds $to$ generalized linearity
   * variances don't add predictably
   
# Simulation

* import for 
* need `for` loops, can rarely vectorize
* `deSolve` package for ODEs
* stochastic ODEs: code your own [Euler-Maryuma](https://en.wikipedia.org/wiki/Euler%E2%80%93Maruyama_method) (easy) or [Milstein](https://en.wikipedia.org/wiki/Milstein_method), or use something from Darren Wilkinson's <#Rpkg|smbfs> package [`library("sos"); findFn("maruyama")`].
